# Generated by Django 2.1.2 on 2018-11-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='intdep',
            name='fro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqfrom', to='riaapp.Req'),
        ),
        migrations.AddField(
            model_name='intdep',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqto', to='riaapp.Req'),
        ),
    ]
