# Generated by Django 2.1.2 on 2018-12-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntDepType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('directional', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='intdep',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deptype', to='riaapp.IntDepType'),
        ),
    ]
