# Generated by Django 2.1.2 on 2018-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0002_auto_20181218_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='indeg',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='req',
            name='outdeg',
            field=models.IntegerField(default=-1),
        ),
    ]
