# Generated by Django 2.1.2 on 2019-05-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	atomic = False
	
	dependencies = [
		('riaapp', '0003_auto_20181218_1728'),
    ]
	
	operations = [
	migrations.CreateModel(
			name='Dep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=1)),
                ('indirect', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deps', models.ManyToManyField(related_name='_path_deps_+', to='riaapp.Dep')),
            ],
        ),
        migrations.RenameModel(
            old_name='IntDepType',
            new_name='DepType',
        ),
        migrations.RemoveField(
            model_name='intdep',
            name='fro',
        ),
        migrations.RemoveField(
            model_name='intdep',
            name='to',
        ),
        migrations.RemoveField(
            model_name='intdep',
            name='typ',
        ),
        migrations.DeleteModel(
            name='IntDep',
        ),
        migrations.AddField(
            model_name='dep',
            name='dep_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='riaapp.DepType'),
        ),
        migrations.AddField(
            model_name='dep',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='riaapp.Req'),
        ),
        migrations.AddField(
            model_name='dep',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='riaapp.Req'),
        ),
    ]
