# Generated by Django 2.1.2 on 2019-05-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0004_auto_20190515_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dep',
            old_name='dest',
            new_name='destination',
        ),
    ]
