# Generated by Django 2.2.3 on 2019-09-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0005_auto_20190515_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepLearnInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField(default=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='riaapp.Dep')),
            ],
        ),
    ]
