# Generated by Django 2.2.3 on 2019-09-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0006_auto_20190909_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deplearninstance',
            name='dep',
        ),
        migrations.AddField(
            model_name='deplearninstance',
            name='dep_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='riaapp.DepType'),
        ),
        migrations.AddField(
            model_name='deplearninstance',
            name='r1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='deplearninstance',
            name='r2',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
