# Generated by Django 2.2.3 on 2019-10-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0007_auto_20190909_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clf_addr', models.CharField(max_length=100)),
                ('vec_addr', models.CharField(max_length=100)),
                ('isAnalyzed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='deplearninstance',
            name='dep_type',
        ),
        migrations.AddField(
            model_name='deplearninstance',
            name='deps',
            field=models.ManyToManyField(related_name='_deplearninstance_deps_+', to='riaapp.DepType'),
        ),
        migrations.AlterField(
            model_name='req',
            name='nlp_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='riaapp.NLPDoc'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='riaapp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='deptype',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='riaapp.Project'),
        ),
        migrations.AddField(
            model_name='req',
            name='issue',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='riaapp.Issue'),
        ),
    ]
