# Generated by Django 2.2.3 on 2019-10-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0008_auto_20191028_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deplearninstance',
            name='deps',
        ),
        migrations.AddField(
            model_name='deplearninstance',
            name='dep_types',
            field=models.ManyToManyField(related_name='_deplearninstance_dep_types_+', to='riaapp.DepType'),
        ),
    ]
