# Generated by Django 2.2.3 on 2019-10-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0010_auto_20191028_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clf_addr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='vec_addr',
            field=models.CharField(default='', max_length=100),
        ),
    ]
