# Generated by Django 2.2.3 on 2019-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0011_auto_20191028_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(default='Task', max_length=80),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
