# Generated by Django 2.2.3 on 2019-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0012_auto_20191108_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='effort',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(default='task', max_length=80),
        ),
    ]
