# Generated by Django 2.2.3 on 2019-11-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0014_depissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='indeg',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='issue',
            name='outdeg',
            field=models.IntegerField(default=-1),
        ),
    ]
