# Generated by Django 2.2.3 on 2019-11-26 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0016_auto_20191122_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='issue',
            name='creator',
            field=models.CharField(default='Someone', max_length=200),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default='ToDo', max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='No Title', max_length=200),
        ),
    ]
